// Neutral icons for the export, so no club artwork ships: a white ladder mark
// (two rails, three rungs) on the #0a0a0a field the manifests already declare.
// Drawn pixel by pixel and encoded with node:zlib, so the bytes are the same on
// every run and there is no image dependency.

import { deflateSync } from 'node:zlib';

const FIELD = [0x0a, 0x0a, 0x0a];
const MARK = [0xff, 0xff, 0xff];

const CRC_TABLE = (() => {
  const t = new Uint32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    t[n] = c >>> 0;
  }
  return t;
})();

export function crc32(buf) {
  let c = 0xffffffff;
  for (const b of buf) c = CRC_TABLE[(c ^ b) & 0xff] ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
}

function chunk(type, data) {
  const len = Buffer.alloc(4);
  len.writeUInt32BE(data.length);
  const body = Buffer.concat([Buffer.from(type, 'ascii'), data]);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(body));
  return Buffer.concat([len, body, crc]);
}

// The mark as rectangles in the unit square, [x0, y0, x1, y1]: two rails and
// the three rungs between them. onMark (the PNGs) and the Android vector both
// draw from this one list.
const RAIL = 0.1;
const RUNG = 0.08;
const RAILS = [
  [0.2, 0.12, 0.2 + RAIL, 0.88],
  [0.8 - RAIL, 0.12, 0.8, 0.88],
];
const RUNGS = [0.27, 0.5, 0.73].map((c) => [0.2 + RAIL, c - RUNG / 2, 0.8 - RAIL, c + RUNG / 2]);
const MARK_RECTS = [...RAILS, ...RUNGS];

/** True when the unit-square point (x, y) is on the mark. */
function onMark(x, y) {
  // Rails include their bottom edge, rungs do not: the original pixel rule.
  const inRail = RAILS.some(([x0, y0, x1, y1]) => x >= x0 && x < x1 && y >= y0 && y <= y1);
  return inRail || RUNGS.some(([x0, y0, x1, y1]) => x >= x0 && x < x1 && y >= y0 && y < y1);
}

/** RGB PNG of the mark, inset by `inset` of the size on every side. */
export function renderPng(size, inset = 0) {
  const art = size * (1 - 2 * inset);
  const offset = (size - art) / 2;
  const raw = Buffer.alloc(size * (size * 3 + 1));
  let p = 0;
  for (let y = 0; y < size; y++) {
    raw[p++] = 0; // filter: none
    for (let x = 0; x < size; x++) {
      const u = (x + 0.5 - offset) / art;
      const v = (y + 0.5 - offset) / art;
      const inside = u >= 0 && u < 1 && v >= 0 && v < 1 && onMark(u, v);
      const [r, g, b] = inside ? MARK : FIELD;
      raw[p++] = r;
      raw[p++] = g;
      raw[p++] = b;
    }
  }
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(size, 0);
  ihdr.writeUInt32BE(size, 4);
  ihdr[8] = 8; // bit depth
  ihdr[9] = 2; // colour type: RGB
  ihdr[10] = 0;
  ihdr[11] = 0;
  ihdr[12] = 0;
  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk('IHDR', ihdr),
    chunk('IDAT', deflateSync(raw, { level: 9 })),
    chunk('IEND', Buffer.alloc(0)),
  ]);
}

/** An ICO that embeds one PNG per size, as modern ICO readers accept. */
export function renderIco(sizes = [16, 32, 48]) {
  const images = sizes.map((s) => renderPng(s));
  const header = Buffer.alloc(6);
  header.writeUInt16LE(0, 0);
  header.writeUInt16LE(1, 2);
  header.writeUInt16LE(images.length, 4);
  const entries = [];
  let offset = 6 + 16 * images.length;
  images.forEach((img, i) => {
    const e = Buffer.alloc(16);
    e[0] = sizes[i] >= 256 ? 0 : sizes[i];
    e[1] = sizes[i] >= 256 ? 0 : sizes[i];
    e[2] = 0;
    e[3] = 0;
    e.writeUInt16LE(1, 4);
    e.writeUInt16LE(24, 6);
    e.writeUInt32LE(img.length, 8);
    e.writeUInt32LE(offset, 12);
    offset += img.length;
    entries.push(e);
  });
  return Buffer.concat([header, ...entries, ...images]);
}

const hex = (rgb) => rgb.map((c) => c.toString(16).padStart(2, '0')).join('').toUpperCase();
const num = (n) => String(Math.round(n * 100) / 100);

function vector(comment, fill, pathData) {
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- ${comment} -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <path
        android:fillColor="#FF${hex(fill)}"
        android:pathData="${pathData}" />
</vector>
`;
}

/** The Android adaptive icon's background layer: the plain field. */
export function androidLauncherBackground() {
  return vector('Generated by the export: the plain field behind the launcher mark.', FIELD, 'M0,0L108,0L108,108L0,108z');
}

/**
 * The adaptive icon's foreground layer: the mark inside the 66dp safe zone of
 * the 108dp canvas, drawn with M, L and z only.
 */
export function androidLauncherForeground() {
  const safe = 66;
  const offset = (108 - safe) / 2;
  const at = (u) => num(offset + u * safe);
  const pathData = MARK_RECTS.map(
    ([x0, y0, x1, y1]) => `M${at(x0)},${at(y0)}L${at(x1)},${at(y0)}L${at(x1)},${at(y1)}L${at(x0)},${at(y1)}z`,
  ).join(' ');
  return vector('Generated by the export: the neutral ladder mark in the 66dp safe zone.', MARK, pathData);
}

// The native apps' launcher art, at EXPORTED paths: the brand map's path rules
// rename the iOS target folder before these are written.
export const MOBILE_LAUNCHER_DIR = 'apps/mobile/android/app/src/main/res/drawable/';
export const MOBILE_IOS_APP_ICON =
  'apps/mobile/ios/ClubLadder/Resources/Assets.xcassets/AppIcon.appiconset/AppIcon-1024.png';

/**
 * Every generated asset, path -> bytes. Overwrites the club artwork. Each path
 * must already be in the export: the caller fails one that is not, so a moved
 * icon cannot leave the club's copy shipping under its new name.
 */
export function generatedAssets() {
  const out = new Map();
  for (const app of ['player', 'admin']) {
    out.set(`apps/${app}/public/apple-touch-icon.png`, renderPng(180));
    out.set(`apps/${app}/public/icon-192.png`, renderPng(192));
    out.set(`apps/${app}/public/icon-512.png`, renderPng(512, 0.1));
    out.set(`apps/${app}/public/favicon.ico`, renderIco());
  }
  // The club's copy is a QR code of its Discord invite. A cloner's server has
  // its own invite, so the export ships the mark in its place.
  out.set('apps/player/public/qr/discord.png', renderPng(512));
  // The native apps: the club's striped red tile and shuttle become the field
  // and the mark. iOS masks the icon itself, so it is square and opaque.
  out.set(`${MOBILE_LAUNCHER_DIR}ic_launcher_background.xml`, Buffer.from(androidLauncherBackground(), 'utf8'));
  out.set(`${MOBILE_LAUNCHER_DIR}ic_launcher_foreground.xml`, Buffer.from(androidLauncherForeground(), 'utf8'));
  out.set(MOBILE_IOS_APP_ICON, renderPng(1024, 0.1));
  return out;
}
