// The three leak checks: infrastructure (plus key shapes), branding, and
// personal values. Every check scans file contents AND file paths.
//
// Output never carries the matched text. Actions logs on a public repo are
// public, so a report line is `path:line: [category] rule <id>` and nothing
// more; a personal hit is reported by its position in the pattern list.

import { globToRegExp } from './select.mjs';

const EMAIL = /[A-Za-z0-9._%+-]+@((?:[A-Za-z0-9-]+\.)+[A-Za-z]{2,})\b/g;

export function compileRules(config, personalPatterns = []) {
  const rules = config.rules.map((r) => ({
    id: r.id,
    category: r.category,
    level: r.level,
    re: new RegExp(r.pattern, r.flags ?? ''),
  }));
  personalPatterns.forEach((p, i) => {
    rules.push({
      id: `personal-${i + 1}`,
      category: 'personal',
      level: 'fail',
      literal: p.toLowerCase(),
    });
  });
  const exceptions = (config.exceptions ?? []).map((e) => ({
    ...e,
    re: globToRegExp(e.path),
    line: e.match ? new RegExp(e.match) : null,
  }));
  const emailAllow = config.emailAllow ?? [];
  return { rules, exceptions, emailAllow };
}

export function emailDomainAllowed(domain, allow) {
  const d = domain.toLowerCase();
  return allow.some((a) => {
    if (a.startsWith('*.')) return d.endsWith(a.slice(1));
    return d === a || d.endsWith(`.${a}`);
  });
}

// An exception names a path glob and a rule id, and optionally a `match` regex
// the line itself must satisfy, so one reviewed line does not excuse the rest
// of its file.
function excepted(compiled, path, ruleId, line) {
  return compiled.exceptions.some(
    (e) => e.rule === ruleId && e.re.test(path) && (!e.line || e.line.test(line)),
  );
}

/** Rules that fire on one line of one file, after exceptions. */
export function lineHits(compiled, path, line) {
  const hits = [];
  const lower = line.toLowerCase();
  for (const rule of compiled.rules) {
    const fired = rule.literal !== undefined ? lower.includes(rule.literal) : rule.re.test(line);
    if (fired && !excepted(compiled, path, rule.id, line)) hits.push(rule);
  }
  for (const m of line.matchAll(EMAIL)) {
    if (!emailDomainAllowed(m[1], compiled.emailAllow) && !excepted(compiled, path, 'email-domain', line)) {
      hits.push({ id: 'email-domain', category: 'email', level: 'fail' });
      break;
    }
  }
  return hits;
}

/**
 * Scans every exported file. `files` maps path -> { text } for text files and
 * path -> { binary: true } otherwise. Binaries are not scanned, but any binary
 * that is neither generated by the export nor on the reviewed list fails.
 */
export function scan(compiled, files, binaryAllow = []) {
  const allow = binaryAllow.map(globToRegExp);
  const findings = [];
  for (const [path, file] of files) {
    for (const hit of lineHits(compiled, path, path)) {
      findings.push({ path, line: 0, category: hit.category, id: hit.id, level: hit.level });
    }
    if (file.binary) {
      if (!file.generated && !allow.some((re) => re.test(path))) {
        findings.push({ path, line: 0, category: 'binary', id: 'unreviewed-binary', level: 'fail' });
      }
      continue;
    }
    const lines = file.text.split('\n');
    for (let i = 0; i < lines.length; i++) {
      for (const hit of lineHits(compiled, path, lines[i])) {
        findings.push({ path, line: i + 1, category: hit.category, id: hit.id, level: hit.level });
      }
    }
  }
  return findings;
}

export function formatFinding(f) {
  return `${f.path}:${f.line}: [${f.category}] rule ${f.id}`;
}

/**
 * Reads the personal patterns: newline-separated, case-insensitive literals.
 * Blank lines are ignored, so a value made only of whitespace counts as unset.
 */
export function parsePatterns(text) {
  if (!text) return [];
  return text
    .split('\n')
    .map((l) => l.trim())
    .filter(Boolean);
}
