// The thin slice of Discord's REST API this bot actually uses.
//
// Role changes go one at a time (PUT/DELETE .../roles/{id}) rather than as one
// PATCH carrying the member's whole role array. The single PATCH is fewer
// requests, and it is the wrong trade here for two reasons:
//
//  - It is all-or-nothing. A bot cannot modify a member whose top role outranks
//    its own, so every exec and admin returns 403 — and with a PATCH that 403
//    would take their @Internal and @Competitive Team down with it. Per-role
//    calls let the parts that CAN sync sync.
//  - It requires sending back every role the member holds, including ones this
//    bot does not manage. Any role added by hand between the read and the write
//    is silently erased.

export type RoleCallResult = 'ok' | 'forbidden' | 'not_found' | 'failed';

/**
 * The outcome of writing to something that may no longer be there.
 *
 * 'gone' is a distinct answer from 'failed' on purpose: a retry fixes a
 * failure and can never fix a deletion, so a caller that cannot tell them
 * apart retries the deletion forever.
 */
export type MessageWriteResult = 'ok' | 'gone' | 'failed';

export interface DiscordApiOptions {
  token: string;
  /** Injectable for tests; defaults to global fetch. */
  fetchImpl?: typeof fetch;
  /** Injectable for tests so a 429 does not actually sleep. */
  sleep?: (ms: number) => Promise<void>;
}

import type { DiscordRole } from './setup.js';

const BASE = 'https://discord.com/api/v10';

// Discord answers a rate limit with retry_after in SECONDS (a float). Two
// retries is the ceiling on purpose: the reconciliation sweep is not
// latency-sensitive and would rather leave a member for the next pass than
// stall behind one bucket.
const MAX_RATE_LIMIT_RETRIES = 2;

/**
 * MANAGE_EVENTS, bit 33. BigInt because Discord's permission mask is a 64-bit
 * value sent as a decimal STRING, and the bits above 52 do not survive Number.
 */
const MANAGE_EVENTS = 1n << 33n;

/** ADMINISTRATOR, bit 3. Implies every other permission. */
const ADMINISTRATOR = 1n << 3n;

export interface ScheduledEventInput {
  name: string;
  description: string;
  /** ISO 8601. Discord refuses a start time in the past. */
  startsAt: string;
  endsAt: string;
  location: string;
}

export class DiscordApi {
  private readonly token: string;
  private readonly fetchImpl: typeof fetch;
  private readonly sleep: (ms: number) => Promise<void>;
  /** Resolved once per process; a bot's own id never changes. */
  private ownUserId: string | null = null;

  constructor(options: DiscordApiOptions) {
    this.token = options.token;
    this.fetchImpl = options.fetchImpl ?? fetch;
    this.sleep = options.sleep ?? ((ms) => new Promise((r) => setTimeout(r, ms)));
  }

  /**
   * A FormData body is passed through UNTOUCHED and WITHOUT a content-type
   * header, because the boundary is generated by fetch and a hand-written
   * `multipart/form-data` header would name a boundary that is not the one in
   * the body. Discord answers that with a 400 that reads as a malformed
   * payload, which is a long way from the real cause.
   *
   * Everything else is JSON, as before.
   */
  private async request(method: string, path: string, body?: unknown): Promise<Response> {
    const isForm = typeof FormData !== 'undefined' && body instanceof FormData;
    let attempt = 0;
    for (;;) {
      const response = await this.fetchImpl(`${BASE}${path}`, {
        method,
        headers: {
          authorization: `Bot ${this.token}`,
          ...(isForm ? {} : { 'content-type': 'application/json' }),
        },
        ...(body === undefined
          ? {}
          : { body: isForm ? (body as FormData) : JSON.stringify(body) }),
      });

      if (response.status !== 429 || attempt >= MAX_RATE_LIMIT_RETRIES) return response;

      // A malformed or missing retry_after must not become NaN and sleep
      // forever; fall back to a second.
      let waitMs = 1000;
      try {
        const body = (await response.clone().json()) as { retry_after?: unknown };
        if (typeof body.retry_after === 'number' && Number.isFinite(body.retry_after)) {
          waitMs = Math.min(Math.max(body.retry_after, 0) * 1000, 10_000);
        }
      } catch {
        // Keep the fallback.
      }
      attempt += 1;
      await this.sleep(waitMs);
    }
  }

  /**
   * The member's current roles, or null if they are not in this guild.
   *
   * Not-in-guild is the ordinary case, not an error: the link is global and a
   * member may only be in one of the club's servers.
   */
  async getMemberRoles(guildId: string, userId: string): Promise<string[] | null> {
    const response = await this.request('GET', `/guilds/${guildId}/members/${userId}`);
    if (response.status === 404) return null;
    if (!response.ok) throw new Error(`GET member -> ${response.status}`);
    const body = (await response.json()) as { roles?: unknown };
    return Array.isArray(body.roles) ? (body.roles as string[]) : [];
  }

  /**
   * Every role in the guild, including @everyone and Discord-managed ones.
   *
   * Filtering happens in setup.ts rather than here: what counts as usable
   * depends on the bot's own position, which this method has no business
   * knowing about.
   */
  async listGuildRoles(guildId: string): Promise<DiscordRole[]> {
    const response = await this.request('GET', `/guilds/${guildId}/roles`);
    if (!response.ok) throw new Error(`GET roles -> ${response.status}`);
    return (await response.json()) as DiscordRole[];
  }

  /**
   * The bot's own user id, resolved from the token and then cached.
   */
  private async getOwnUserId(): Promise<string> {
    if (this.ownUserId) return this.ownUserId;
    const response = await this.request('GET', '/users/@me');
    if (!response.ok) throw new Error(`GET /users/@me -> ${response.status}`);
    const { id } = (await response.json()) as { id?: string };
    if (!id) throw new Error('GET /users/@me returned no id');
    this.ownUserId = id;
    return id;
  }

  /**
   * The bot's own highest role position in a guild.
   *
   * Needed because Discord refuses to let a bot create or assign a role at or
   * above its own, and a wired-up role above the bot fails on every single
   * sweep while looking perfectly configured.
   *
   * The user id has to be spelled out here. `@me` is only a valid stand-in on
   * `/users/@me`; on `/guilds/{id}/members/{user_id}` Discord parses the final
   * segment as a number and answers 400 NUMBER_TYPE_COERCE. That 400 used to
   * surface to the user as "I need Manage Roles", which sent people to fix a
   * permission that was never the problem.
   */
  async getOwnRolePosition(guildId: string): Promise<number> {
    const userId = await this.getOwnUserId();
    const member = await this.request('GET', `/guilds/${guildId}/members/${userId}`);
    if (!member.ok) throw new Error(`GET member -> ${member.status}`);
    const { roles } = (await member.json()) as { roles?: string[] };
    const all = await this.listGuildRoles(guildId);
    const mine = new Set(roles ?? []);
    // A bot with no roles beyond @everyone has position 0 and can assign
    // nothing, which the caller reports rather than treating as "unlimited".
    return all
      .filter((r) => mine.has(r.id))
      .reduce((highest, r) => Math.max(highest, r.position), 0);
  }

  /**
   * Create a role, with NO permissions.
   *
   * `permissions: '0'` is not a tidy default, it is the whole safety property.
   * Discord copies @everyone's permissions onto a new role when the field is
   * omitted, so on a server where @everyone can, say, manage messages, running
   * /setup would silently mint nine roles carrying that power. Sending "0"
   * explicitly makes a created role purely a label until a human grants it
   * something.
   */
  async createGuildRole(guildId: string, name: string): Promise<DiscordRole> {
    const response = await this.request('POST', `/guilds/${guildId}/roles`, {
      name,
      permissions: '0',
      mentionable: false,
      hoist: false,
    });
    if (!response.ok) throw new Error(`POST role "${name}" -> ${response.status}`);
    return (await response.json()) as DiscordRole;
  }

  /**
   * Post a message to a channel. Used by the audit log and the session pings.
   *
   * Returns a boolean instead of throwing, and the reason is the same one that
   * governs roleCall: the audit log is a RECORD of work, never a gate on it. A
   * missing channel, a revoked permission or a 429 must not turn a completed
   * unlink into a failed one, so the caller gets a value it is free to ignore.
   */
  async createMessage(channelId: string, payload: unknown): Promise<boolean> {
    try {
      const response = await this.request('POST', `/channels/${channelId}/messages`, payload);
      return response.ok;
    } catch {
      return false;
    }
  }

  /**
   * Post and hand back the message id, for anything that has to find the
   * message again later. The session pings do not — a ping is a moment, and
   * nothing edits or withdraws one — which is why createMessage above answers a
   * bare boolean and this exists alongside it rather than replacing it.
   */
  async postMessage(channelId: string, payload: unknown): Promise<string | null> {
    try {
      const response = await this.request('POST', `/channels/${channelId}/messages`, payload);
      if (!response.ok) {
        console.error(`[bot] post message to ${channelId} -> ${response.status}`);
        return null;
      }
      const { id } = (await response.json()) as { id?: string };
      return id ?? null;
    } catch (error) {
      console.error(`[bot] post message to ${channelId} threw:`, error);
      return null;
    }
  }

  /**
   * Post with a file attached, for the one relay that carries a screenshot.
   *
   * Discord takes an attachment as multipart: `payload_json` holding what would
   * otherwise be the whole body, plus `files[0]` holding the bytes. The
   * attachment must ALSO be declared in payload_json.attachments with the
   * matching id, or the upload is accepted and the message renders without it —
   * a silent half-success, which is why the declaration is built here rather
   * than left to callers.
   *
   * Falls back to a plain post when there is no file, so a caller does not have
   * to branch: a report with no screenshot and a report whose screenshot could
   * not be fetched take the same path, and neither loses the words.
   */
  async postMessageWithFile(
    channelId: string,
    payload: Record<string, unknown>,
    file: { filename: string; contentType: string; bytes: Uint8Array } | null
  ): Promise<string | null> {
    if (!file) return this.postMessage(channelId, payload);

    const form = new FormData();
    form.append(
      'payload_json',
      JSON.stringify({
        ...payload,
        attachments: [{ id: 0, filename: file.filename }],
      })
    );
    // Copied into a fresh ArrayBuffer: a Uint8Array that is a VIEW onto a
    // larger buffer (which is what Buffer.concat slices give you) would
    // otherwise upload the whole underlying buffer.
    form.append(
      'files[0]',
      new Blob([file.bytes.slice().buffer as ArrayBuffer], { type: file.contentType }),
      file.filename
    );

    try {
      const response = await this.request('POST', `/channels/${channelId}/messages`, form);
      if (!response.ok) {
        console.error(`[bot] post message with file to ${channelId} -> ${response.status}`);
        return null;
      }
      const { id } = (await response.json()) as { id?: string };
      return id ?? null;
    } catch (error) {
      console.error(`[bot] post message with file to ${channelId} threw:`, error);
      return null;
    }
  }

  /**
   * Edit a message the bot itself sent. Needs no permission beyond being its
   * author — Discord refuses an edit of anybody else's message outright, with
   * no permission that grants it.
   *
   * THREE ANSWERS, NOT TWO, and 'gone' is the one that matters.
   *
   * A message somebody deleted by hand answers 404 to every subsequent PATCH.
   * Folded into 'failed' that becomes an unbounded retry loop: nothing is
   * recorded, the next tick computes the identical diff, and the relay hammers
   * a dead message id every five minutes for as long as the announcement
   * exists. The sequence that gets there is the natural one — the Discord copy
   * looked wrong, somebody removed it, then the author corrected the source.
   *
   * Distinguishing it lets the caller settle the diff instead. Same reason
   * deleteMessage below counts 404 as success.
   */
  async editMessage(
    channelId: string,
    messageId: string,
    payload: unknown
  ): Promise<MessageWriteResult> {
    try {
      const response = await this.request(
        'PATCH',
        `/channels/${channelId}/messages/${messageId}`,
        payload
      );
      if (response.ok) return 'ok';
      if (response.status === 404) return 'gone';
      console.error(`[bot] edit message ${messageId} in ${channelId} -> ${response.status}`);
      return 'failed';
    } catch {
      return 'failed';
    }
  }

  /**
   * Delete a message the bot sent.
   *
   * MANAGE_MESSAGES is required only to delete SOMEBODY ELSE'S message, so this
   * needs nothing granted — which is why the relay ships without the preflight
   * that the scheduled events needed.
   *
   * 404 counts as success, same as a deleted scheduled event: whoever removed
   * it by hand already achieved what this call was for, and calling that a
   * failure would retry it every tick forever.
   */
  async deleteMessage(channelId: string, messageId: string): Promise<boolean> {
    try {
      const response = await this.request(
        'DELETE',
        `/channels/${channelId}/messages/${messageId}`
      );
      return response.ok || response.status === 204 || response.status === 404;
    } catch {
      return false;
    }
  }

  /**
   * Does the bot hold MANAGE_EVENTS in this guild?
   *
   * CHECKED BEFORE TRYING, and this is the one method here that exists purely
   * so a failure is legible. The bot is invited with Manage Roles (see the
   * bringup doc) and nothing else, so on any server set up before this feature
   * existed the answer is NO — every scheduled-event call answers a bare 403,
   * and 403 from Discord says nothing about which permission was missing. The
   * getOwnRolePosition comment records what that costs: a 400 that surfaced as
   * "I need Manage Roles" sent people to fix a permission that was never the
   * problem. One read here turns the same class of mistake into a log line that
   * names the fix.
   *
   * Permissions are the OR of every role the bot holds, @everyone included —
   * that role is the one whose id equals the guild id. Administrator is checked
   * separately because it implies everything and is how many small servers
   * actually run their bots.
   */
  async hasManageEvents(guildId: string): Promise<boolean> {
    const userId = await this.getOwnUserId();
    const member = await this.request('GET', `/guilds/${guildId}/members/${userId}`);
    if (!member.ok) throw new Error(`GET member -> ${member.status}`);
    const { roles } = (await member.json()) as { roles?: string[] };

    // @everyone applies whether or not it is listed on the member.
    const mine = new Set([...(roles ?? []), guildId]);
    const all = await this.listGuildRoles(guildId);

    const held = all
      .filter((r) => mine.has(r.id))
      // The field is a STRING of a 64-bit mask. Number() would lose the high
      // bits — MANAGE_EVENTS is bit 33, which survives, but bits above 52 do
      // not, and a silently-truncated mask is the kind of bug that answers
      // correctly right up until Discord adds a permission.
      .reduce((acc, r) => acc | BigInt(r.permissions ?? '0'), 0n);

    return (held & ADMINISTRATOR) === ADMINISTRATOR || (held & MANAGE_EVENTS) === MANAGE_EVENTS;
  }

  /**
   * Create an EXTERNAL scheduled event — the kind that shows in the Events tab
   * with a location rather than a voice channel.
   *
   * Returns the new event's id, or null. Never throws for a Discord-side
   * refusal: one tournament Discord will not accept must not stop the rest of
   * the run, exactly as one unpostable ping does not stop the others.
   */
  async createScheduledEvent(guildId: string, event: ScheduledEventInput): Promise<string | null> {
    try {
      const response = await this.request('POST', `/guilds/${guildId}/scheduled-events`, {
        name: event.name,
        description: event.description,
        scheduled_start_time: event.startsAt,
        scheduled_end_time: event.endsAt,
        // 3 = EXTERNAL. The other types (1 STAGE, 2 VOICE) require a channel_id
        // and would tie a club tournament to a voice room nobody uses.
        entity_type: 3,
        // REQUIRED for EXTERNAL, and Discord rejects the whole call without it
        // rather than defaulting. An unset location setting becomes the club
        // name rather than an empty string for that reason.
        entity_metadata: { location: event.location },
        privacy_level: 2, // GUILD_ONLY, the only value Discord accepts.
      });
      if (!response.ok) {
        console.error(
          `[bot] create scheduled event "${event.name}" -> ${response.status}` +
            (response.status === 403 ? ' (missing MANAGE_EVENTS?)' : '')
        );
        return null;
      }
      const { id } = (await response.json()) as { id?: string };
      return id ?? null;
    } catch (error) {
      console.error(`[bot] create scheduled event "${event.name}" threw:`, error);
      return null;
    }
  }

  /**
   * Push changed details onto an existing event.
   *
   * `patchTimes` false omits the schedule entirely, because Discord refuses to
   * retime an event that has already started. Sending it anyway would make
   * every rename of a running tournament fail, and the caller would retry the
   * same refused call on every tick.
   *
   * 'gone' is separated from 'failed' for the reason editMessage spells out: an
   * event an exec deleted from the Events tab by hand answers 404 to every
   * PATCH after it, and a caller that reads that as "retry me" does exactly
   * that until the tournament finishes.
   */
  async modifyScheduledEvent(
    guildId: string,
    eventId: string,
    event: ScheduledEventInput,
    patchTimes = true
  ): Promise<MessageWriteResult> {
    try {
      const response = await this.request(
        'PATCH',
        `/guilds/${guildId}/scheduled-events/${eventId}`,
        {
          name: event.name,
          description: event.description,
          ...(patchTimes
            ? {
                scheduled_start_time: event.startsAt,
                scheduled_end_time: event.endsAt,
                // entity_type travels with the schedule: Discord validates
                // entity_metadata against it, and an EXTERNAL event needs both
                // present or neither.
                entity_type: 3,
                entity_metadata: { location: event.location },
              }
            : {}),
        }
      );
      if (response.ok) return 'ok';
      if (response.status === 404) return 'gone';
      console.error(`[bot] modify scheduled event ${eventId} -> ${response.status}`);
      return 'failed';
    } catch {
      return 'failed';
    }
  }

  /**
   * Cancel an event by deleting it.
   *
   * 404 counts as success: somebody removing it in Discord by hand has already
   * achieved what this call was for, and treating that as a failure would retry
   * it every tick forever.
   */
  async deleteScheduledEvent(guildId: string, eventId: string): Promise<boolean> {
    try {
      const response = await this.request(
        'DELETE',
        `/guilds/${guildId}/scheduled-events/${eventId}`
      );
      return response.ok || response.status === 204 || response.status === 404;
    } catch {
      return false;
    }
  }

  addRole(guildId: string, userId: string, roleId: string): Promise<RoleCallResult> {
    return this.roleCall('PUT', guildId, userId, roleId);
  }

  removeRole(guildId: string, userId: string, roleId: string): Promise<RoleCallResult> {
    return this.roleCall('DELETE', guildId, userId, roleId);
  }

  private async roleCall(
    method: 'PUT' | 'DELETE',
    guildId: string,
    userId: string,
    roleId: string
  ): Promise<RoleCallResult> {
    let response: Response;
    try {
      response = await this.request(method, `/guilds/${guildId}/members/${userId}/roles/${roleId}`);
    } catch {
      return 'failed';
    }
    if (response.ok || response.status === 204) return 'ok';
    // THE IMPORTANT ONE. 403 is the expected answer for every exec and admin,
    // because a bot cannot touch a member who outranks it. Returning a value
    // rather than throwing is what stops one predictable 403 aborting a sweep
    // and leaving everybody else's drift unrepaired.
    if (response.status === 403) return 'forbidden';
    if (response.status === 404) return 'not_found';
    return 'failed';
  }
}

/**
 * Replace the deferred "thinking..." message with the real one.
 *
 * A standalone function, not a DiscordApi method, because it authenticates with
 * the INTERACTION token rather than the bot token — the webhook route carries
 * its own credential. Passing a bot token here would be rejected.
 *
 * Never throws: it runs after the work is already done and committed, and an
 * unhandled rejection in a fire-and-forget path takes the process down with it.
 * A lost message is bad; a bot that exits because it could not describe what it
 * just did is worse.
 */
export async function editDeferredReply(
  applicationId: string,
  interactionToken: string,
  payload: unknown,
  fetchImpl: typeof fetch = fetch
): Promise<boolean> {
  try {
    const response = await fetchImpl(
      `${BASE}/webhooks/${applicationId}/${interactionToken}/messages/@original`,
      {
        method: 'PATCH',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify(payload),
      }
    );
    return response.ok;
  } catch {
    return false;
  }
}
