// Reading a TOURNAMENT check-in QR that was scanned inside the app.
//
// The mirror of lib/checkin-scan.ts, and it exists for the same reason that one
// does: the two codes are the same 48 hex characters against two different
// tables, and only their SHAPE tells them apart.
//
//   session     <base>/checkin/<48 hex>            -> session_checkin_tokens
//   tournament  <base>/tournaments/checkin?token=  -> tournament_checkin_tokens
//
// Deep import rather than the '@badminton/shared' barrel: this module is pulled
// into the client bundle by the tournament check-in client, and the barrel
// re-exports the whole package. constants.ts has no dependencies.
import { CHECKIN_TOKEN_REGEX } from '@badminton/shared/src/utils/constants';

/**
 * What the camera decoded, classified.
 *
 * Three outcomes rather than `string | null`, because the screen has three
 * genuinely different things to say. Collapsing them was the old bug: a member
 * who pointed this scanner at the code taped to the gym door — a real check-in
 * code, generated by this same app — was told "That does not look like a
 * check-in code", which is simply untrue and leaves them with nothing to do
 * about it.
 */
export type TournamentScan =
  | { kind: 'token'; token: string }
  /** A SESSION door code. Ours, valid, and for the other flow entirely. */
  | { kind: 'session-code' }
  /** Anything else: a poster, a wifi QR, a stranger's profile link. */
  | { kind: 'unreadable' };

/** The path form of a session check-in QR. The optional leading segment absorbs
 *  a basePath, exactly as CHECKIN_PATH does in checkin-scan.ts. */
const SESSION_CHECKIN_PATH = /^(?:\/[^/]+)?\/checkin\/([^/?#]+)\/?$/;

/**
 * Classifies whatever the camera decoded for the tournament check-in flow.
 *
 * The QR an exec displays encodes a full URL, so a phone's native camera app
 * lands on `/tournaments/checkin?token=…` and checks in without ever opening
 * the in-app scanner. This function is for the other half: someone already in
 * the app, pointing the in-app scanner at that same printed code.
 *
 * A BARE 48-hex string is accepted as a token, and that is a deliberate
 * ambiguity rather than an oversight: a bare session token and a bare
 * tournament token are indistinguishable, so it is classified as a tournament
 * token and the server refuses it if it is not one. Nothing generates bare
 * codes today; the branch exists so a plain-text code would still work.
 */
export function classifyTournamentScan(raw: string): TournamentScan {
  const trimmed = raw.trim();
  if (!trimmed) return { kind: 'unreadable' };

  // Plain-text code — see the note above on why this is claimed here.
  if (CHECKIN_TOKEN_REGEX.test(trimmed)) return { kind: 'token', token: trimmed };

  // One parse covers absolute and relative alike: an absolute URL ignores the
  // base, a relative one resolves against it. The base is never read back, and
  // the host is deliberately not checked — staging, production and the domain
  // being retired all print real codes for the same club.
  let url: URL;
  try {
    url = new URL(trimmed, 'http://scan.invalid');
  } catch {
    return { kind: 'unreadable' };
  }

  const token = url.searchParams.get('token');
  if (token && CHECKIN_TOKEN_REGEX.test(token)) return { kind: 'token', token };

  // A session door code. Recognised so the screen can say which code this is
  // and which one it wants, instead of calling a valid code invalid.
  const sessionToken = SESSION_CHECKIN_PATH.exec(url.pathname)?.[1];
  if (sessionToken) {
    // decodeURIComponent throws on a malformed escape (`%zz`); a scan of
    // arbitrary text must not crash here.
    let decoded: string;
    try {
      decoded = decodeURIComponent(sessionToken);
    } catch {
      return { kind: 'unreadable' };
    }
    if (CHECKIN_TOKEN_REGEX.test(decoded)) return { kind: 'session-code' };
  }

  return { kind: 'unreadable' };
}

/** Said when the scanner reads a SESSION door code. True, and it names the way
 *  forward — the tournament code is a different piece of paper. */
export const SESSION_CODE_SCAN_MESSAGE =
  "That's the session check-in code for tonight's practice, not the tournament one. " +
  'Point the camera at the code the exec is showing for the tournament.';

/** Said for everything else. One message for every kind of miss: a member
 *  holding a phone at the door gains nothing from knowing whether the code was
 *  malformed or simply somebody else's. */
export const UNREADABLE_TOURNAMENT_SCAN_MESSAGE =
  "That doesn't look like a tournament check-in code. Point the camera at the code the exec is showing.";
