-- ============================================================
-- 00007_seed.sql — Development seed data
-- ============================================================
-- Commented out for production — clean tables on reset.
