import { describe, it, expect } from 'vitest';
import {
  classifyTournamentScan,
  SESSION_CODE_SCAN_MESSAGE,
  UNREADABLE_TOURNAMENT_SCAN_MESSAGE,
} from '../tournament-scan';

// The tournament scanner's half of "which of the club's two identically shaped
// codes is this?". checkin-scan.test.ts asserts the other direction: that the
// SESSION scanner refuses a tournament code. Together they are the pair.

const TOKEN = 'a'.repeat(48);
const OTHER = '0123456789abcdef'.repeat(3); // 48 hex, a different token

describe('classifyTournamentScan — codes that are ours', () => {
  it('reads the absolute URL the admin console encodes', () => {
    expect(classifyTournamentScan(`https://sfubadminton.com/tournaments/checkin?token=${TOKEN}`))
      .toEqual({ kind: 'token', token: TOKEN });
  });

  it('reads the same path relative', () => {
    expect(classifyTournamentScan(`/tournaments/checkin?token=${OTHER}`))
      .toEqual({ kind: 'token', token: OTHER });
  });

  it('tolerates extra query parameters and a hash', () => {
    expect(classifyTournamentScan(`https://example.org/tournaments/checkin?utm=poster&token=${TOKEN}#x`))
      .toEqual({ kind: 'token', token: TOKEN });
  });

  it('trims surrounding whitespace', () => {
    expect(classifyTournamentScan(`  https://example.org/tournaments/checkin?token=${TOKEN}  `))
      .toEqual({ kind: 'token', token: TOKEN });
  });

  it('does not care which host the code names', () => {
    // Staging, production and the domain being retired all print real codes;
    // the token is resolved server-side, so the host proves nothing either way.
    expect(classifyTournamentScan(`https://badminton.polardev.org/tournaments/checkin?token=${OTHER}`))
      .toEqual({ kind: 'token', token: OTHER });
  });
});

describe('classifyTournamentScan — the session door code', () => {
  // THE DEFECT THIS TYPE EXISTS FOR. A member points the tournament scanner at
  // the code taped to the gym door. It is a real check-in code, generated by
  // this same app, against a different table — and the screen used to answer
  // "That does not look like a check-in code", which is untrue and leaves them
  // with nothing to do next.

  it('recognises the absolute session URL as a session code, not as noise', () => {
    expect(classifyTournamentScan(`https://sfubadminton.com/checkin/${TOKEN}`))
      .toEqual({ kind: 'session-code' });
  });

  it('recognises it relative and through a basePath prefix', () => {
    expect(classifyTournamentScan(`/checkin/${TOKEN}`)).toEqual({ kind: 'session-code' });
    expect(classifyTournamentScan(`https://example.org/player/checkin/${OTHER}`))
      .toEqual({ kind: 'session-code' });
  });

  it('tolerates a trailing slash, a query and a hash on it', () => {
    expect(classifyTournamentScan(`https://example.org/checkin/${TOKEN}/`)).toEqual({ kind: 'session-code' });
    expect(classifyTournamentScan(`https://example.org/checkin/${TOKEN}?utm=poster`)).toEqual({ kind: 'session-code' });
    expect(classifyTournamentScan(`https://example.org/checkin/${TOKEN}#x`)).toEqual({ kind: 'session-code' });
  });

  it('says something true about it, and names the other code', () => {
    // The old message asserted the code was not a check-in code. This one says
    // which check-in code it is and which one the screen wants.
    expect(SESSION_CODE_SCAN_MESSAGE).toContain('session check-in code');
    expect(SESSION_CODE_SCAN_MESSAGE).toContain('tournament');
    expect(SESSION_CODE_SCAN_MESSAGE).not.toMatch(/not (a|valid)/i);
  });

  it('does not mistake a wrong-shaped token in the session path for one', () => {
    expect(classifyTournamentScan('https://example.org/checkin/not-a-token'))
      .toEqual({ kind: 'unreadable' });
    expect(classifyTournamentScan(`https://example.org/checkin/${'a'.repeat(47)}`))
      .toEqual({ kind: 'unreadable' });
  });
});

describe('classifyTournamentScan — everything else', () => {
  it('refuses a player profile QR', () => {
    expect(
      classifyTournamentScan('https://example.org/challenges/new?opponent=3f2504e0-4f89-41d3-9a0c-0305e82c3301'),
    ).toEqual({ kind: 'unreadable' });
  });

  it('refuses an unrelated QR code entirely', () => {
    expect(classifyTournamentScan('https://www.instagram.com/sfubadminton')).toEqual({ kind: 'unreadable' });
    expect(classifyTournamentScan('WIFI:S:GymGuest;T:WPA;P:hunter2;;')).toEqual({ kind: 'unreadable' });
    expect(classifyTournamentScan('just some text')).toEqual({ kind: 'unreadable' });
  });

  it('refuses an empty or whitespace-only scan', () => {
    expect(classifyTournamentScan('')).toEqual({ kind: 'unreadable' });
    expect(classifyTournamentScan('   ')).toEqual({ kind: 'unreadable' });
  });

  it('refuses a ?token= that is not token-shaped', () => {
    expect(classifyTournamentScan('https://example.org/tournaments/checkin?token=nope'))
      .toEqual({ kind: 'unreadable' });
    expect(classifyTournamentScan(`https://example.org/tournaments/checkin?token=${'A'.repeat(48)}`))
      .toEqual({ kind: 'unreadable' });
  });

  it('refuses rather than throws on a malformed percent-escape', () => {
    expect(classifyTournamentScan('https://example.org/checkin/%zz')).toEqual({ kind: 'unreadable' });
  });

  it('offers a message that points at the right piece of paper', () => {
    expect(UNREADABLE_TOURNAMENT_SCAN_MESSAGE).toContain('tournament check-in code');
  });
});

describe('classifyTournamentScan — the ambiguity that cannot be resolved', () => {
  it('claims a BARE 48-hex string as a tournament token', () => {
    // A bare session token and a bare tournament token are the same 48
    // characters with nothing around them; no client-side function can tell
    // them apart. It is claimed here and the server refuses it if it is wrong.
    // Nothing generates bare codes today — both QRs encode full URLs — so this
    // branch exists for a plain-text code that has never been printed.
    expect(classifyTournamentScan(TOKEN)).toEqual({ kind: 'token', token: TOKEN });
  });
});
